---
title: "GEDI Data Exploration"
output: html_document
date: "2024-03-28"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(rGEDI)
library(dplyr)
library(ggplot2)
library(sf)
```

## Download GEDI data
```{r}
# Study area boundary box coordinates
ul_lat <- 32.47
ul_lon <- -92.01
lr_lat <- 32.43
lr_lon <- -91.93

# Specifying the date range
daterange=c("2019-07-01","2020-05-22")

# Get path to GEDI data
gLevel1B<-gedifinder(product="GEDI01_B",ul_lat, ul_lon, lr_lat, lr_lon,version="002",daterange=daterange)
gLevel2A<-gedifinder(product="GEDI02_A",ul_lat, ul_lon, lr_lat, lr_lon,version="002",daterange=daterange)
gLevel2B<-gedifinder(product="GEDI02_B",ul_lat, ul_lon, lr_lat, lr_lon,version="002",daterange=daterange)

```

```{r}
# Set output dir for downloading the files
outdir=setwd("~/Desktop/GEDI")

# Downloading GEDI data
gediDownload(filepath=gLevel1B,outdir=outdir)
gediDownload(filepath=gLevel2A,outdir=outdir)
gediDownload(filepath=gLevel2B,outdir=outdir)
```

```{r}
# Reading GEDI data
gedilevel1b<-readLevel1B(level1Bpath = file.path(outdir,"GEDI01_B_2020243151139_O09724_03_T07457_02_005_01_V002.h5"))
gedilevel2a<-readLevel2A(level2Apath = file.path(outdir,"GEDI02_A_2019108080338_O01964_T05337_02_001_01_sub.h5"))
gedilevel2b<-readLevel2B(level2Bpath = file.path(outdir,"GEDI02_B_2019108080338_O01964_T05337_02_001_01_sub.h5"))

```

## Get data into workable form
```{r}
ymax <- 32.47
xmin <- -92.01
ymin <- 32.43
xmax <- -91.93

level1bGeo <- getLevel1BGeo(level1b=gedilevel1b,select=c("elevation_bin0"))

level1b_clip_bb <- clipLevel1BGeo(level1bGeo, xmin, xmax, ymin, ymax)

level1b_clip_bb$shot_number<-as.character(level1b_clip_bb$shot_number)

# Create simple features data frame
level1bGeo_sf <- st_as_sf(level1b_clip_bb,                         
           coords = c("longitude_bin0", "latitude_bin0"),
           crs = 4326)

```

## Manual approach (DONT RUN)
```{r}
# Converting shot_number as "integer64" to "character"
level1bGeo_test$shot_number<-as.character(level1bGeo_test$shot_number)

level1bGeo_test <- level1bGeo %>%
  filter(latitude_bin0 >= 32.45 & latitude_bin0 <= 32.46) %>%
  filter(longitude_bin0 >=-92 & longitude_bin0 <=-91.96)

# Create simple features data frame
level1bGeo_sf <- st_as_sf(level1bGeo_test,                         
           coords = c("longitude_bin0", "latitude_bin0"),
           crs = 4326)
```

## Mapping study area
```{r}
library(tmap)

tmap_mode("view")

tm_shape(level1bGeo_sf) +
  tm_dots()
```

## Full waveform information
```{r}
# Extracting GEDI full-waveform for a given shotnumber
wf <- getLevel1BWF(gedilevel1b, shot_number="97240100300200081")

par(mfrow = c(1,2), mar=c(4,4,1,1), cex.axis = 1.5)

plot(wf, relative=FALSE, polygon=TRUE, type="l", lwd=2, col="forestgreen",
     xlab="Waveform Amplitude", ylab="Elevation (m)")
grid()
plot(wf, relative=TRUE, polygon=FALSE, type="l", lwd=2, col="forestgreen",
     xlab="Waveform Amplitude (%)", ylab="Elevation (m)")
grid()
```


